/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./*.html', './pages/*.html', './js/*.js'],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-variant': '#353534',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        primary: '#e9c086',
        'primary-container': '#af8b55',
        'on-primary': '#442b00',
        'on-primary-container': '#3b2500',
        secondary: '#c6c6c7',
        'secondary-container': '#454747',
        'on-secondary': '#2f3131',
        tertiary: '#c8c6c5',
        'on-tertiary': '#313030',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d2c4b6',
        'on-background': '#e5e2e1',
        outline: '#9b8f81',
        'outline-variant': '#4e453a',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        bronze: '#a17e4a',
        obsidian: '#0a0a0a',
        'dim-gray': '#333333',
        'stark-white': '#ffffff',
      },
      fontFamily: {
        display: ['Montserrat', 'sans-serif'],
        heading: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['100px', { lineHeight: '0.9', letterSpacing: '-0.04em', fontWeight: '900' }],
        'display-md': ['64px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' }],
        'headline-xl': ['56px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'stat-number': ['80px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' }],
      },
      spacing: {
        'section-gap': '160px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        gutter: '32px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
      },
      borderRadius: {
        DEFAULT: '0',
        lg: '0',
        xl: '0',
        full: '9999px',
      },
      animation: {
        reveal: 'reveal 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        reveal: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
